-- SQL Challenges
SELECT * FROM Products;
SELECT * FROM products Where Price = 1400;
SELECT * FROM products Where Price BETWEEN 11.99 AND 13.99;
SELECT * FROM PRODUCTS WHERE Not Price = 11.99;
SELECT * FROM PRODUCTS order by Price Desc;
SELECT * FROM EMPLOYEES WHERE MiddleInitial IS NULL OR MiddleInitial = ' ';
SELECT DISTINCT Price from products;
SELECT * from EMPLOYEES WHERE FirstName LIKE 'J%';
SELECT * from products where name = 'MacBook';
SELECT * FROM PRODUCTS WHERE ONSALE =1; -- WHERE OR ONSALE = TRUE;
SELECT AVG(PRICE) AS 'AVERAGE PRICE' FROM PRODUCTS;
SELECT ROUND(AVG(PRICE), 2) AS 'AVERAGE PRICE' FROM PRODUCTS;
SELECT * FROM EMPLOYEES WHERE MiddleInitial IS NULL AND TITLE = 'GEEK SQUAD';
SELECT * FROM PRODUCTS WHERE STOCKLEVEL BETWEEN 500 AND 1200 
ORDER BY PRICE ASC, STOCKLEVEL DESC;
